### ISSUE TITLE
Libhdfs3 repo path issue

### ISSUE THREAD

**Issue by sharpyfox** [datacratic/platform-deps#3]
Hello guys. Looks like *libhdfs3* submodule was added using `ssh` url, instead `https`
```
git@github.com:datacratic/libhdfs3.git
```
instead
```
https://github.com/datacratic/libhdfs3.git
```

This creates difficulties for our CI system. It failed to clone this repo using https protocol for building `rtbkit` (it doesn't have authorized github ssh key). Is it possible to change submodule url to *https*? All other modles was added using *https* urls. Thanks.

**Comment by RAttab** [comment]
Will be fixed shortly. Thanks for raising the issue.

**Comment by wsourdeau** [comment]
Hello, I have updated the reference, can you confirm that it works for you?

**Comment by RAttab** [comment]
Little update, this dependency is going to break when built due to an additional package requirement that needs to be installed at the system level. We don't really want to push that kind of update on the community since you guys have no uses for it. In the future this will be prevented via the rtbkit-deps fork but right now, we're trying to figure out how best to remove the dependency and keep it active for us internally.

A fix should be available shortly.

**Comment by RAttab** [comment]
hdfs was removed from the main target so it should no longer be built by default. This along with the submodule URL should fix all issues related to the new hdfs dependency.

**Comment by wsourdeau** [comment]
@sharpyfox  can you confirm that it works for you?

**Comment by sharpyfox** [comment]
@RAttab @wsourdeau , thanks for the quick fix. Now it works ok for us :+1:. Sorry for delay with confirmation.
